#!/bin/bash
set -e
zookeeper-3.4.12/bin/zkServer.sh start
cp "$1.java" Main.java
export CLASSPATH=.\
:jars/audience-annotations-0.8.0.jar\
:jars/curator-client-4.0.1.jar\
:jars/curator-framework-4.0.1.jar\
:jars/curator-recipes-4.0.1.jar\
:jars/guava-27.0-jre.jar\
:jars/log4j-1.2.17.jar\
:jars/slf4j-api-1.7.25.jar\
:jars/slf4j-log4j12-1.7.25.jar\
:jars/zookeeper-3.4.12.jar\
:.
javac Main.java
pids=""
for i in `seq 0 2`; do
   java Main &
   pids="$pids $!"
done
wait $pids # for output to show up in tech.io
